[package]
name = "rust_static_analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

error-chain = "0.12.4"
pretty_assertions = "1.2.1"
serde = "1.0.143"
serde_derive = "1.0.143"